# Generated by Django 6.0.6 on 2026-06-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Reservation Assistance', 'Reservation Assistance'), ('Private Event Enquiry', 'Private Event Enquiry'), ('Feedback / Review', 'Feedback / Review'), ('Catering Request', 'Catering Request'), ('Press & Media', 'Press & Media')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
