# Generated by Django 6.0.6 on 2026-08-04 07:19

import User_Dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(default=User_Dashboard.models.generate_res_ref, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('guests', models.PositiveIntegerField(default=2)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('12:00', '12:00 PM (Lunch)'), ('12:30', '12:30 PM (Lunch)'), ('13:00', '1:00 PM (Lunch)'), ('13:30', '1:30 PM (Lunch)'), ('14:00', '2:00 PM (Lunch)'), ('18:00', '6:00 PM (Dinner)'), ('18:30', '6:30 PM (Dinner)'), ('19:00', '7:00 PM (Dinner)'), ('19:30', '7:30 PM (Dinner)'), ('20:00', '8:00 PM (Dinner)'), ('20:30', '8:30 PM (Dinner)'), ('21:00', '9:00 PM (Dinner)')], max_length=10)),
                ('occasion', models.CharField(blank=True, choices=[('casual', 'Casual Dining'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('date', 'Date Night'), ('business', 'Business Meal'), ('celebration', 'Special Celebration')], default='casual', max_length=50)),
                ('seating_preference', models.CharField(blank=True, choices=[('main', 'Main Dining Room'), ('window', 'Window Table'), ('booth', 'Cozy Booth'), ('terrace', 'Outdoor Terrace'), ('chef', "Chef's Table / Counter"), ('private', 'Private Dining Room')], default='main', max_length=50)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate calories per serving', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='chef_notes',
            field=models.TextField(blank=True, help_text="Chef's pairing or preparation notes"),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Comma-separated ingredients e.g. Wagyu Beef, Black Truffle, Rosemary'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='prep_time',
            field=models.PositiveIntegerField(default=20, help_text='Prep time in minutes'),
        ),
    ]
