# Generated by Django 5.2.6 on 2026-08-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Dashboard', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulinaryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.CharField(default='7:00 PM', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=150.0, max_digits=8)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('discount_percent', models.PositiveIntegerField(default=10)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Savoir Fine Dining', max_length=200)),
                ('phone', models.CharField(default='+1 (212) 555-0192', max_length=50)),
                ('email', models.EmailField(default='reservations@savoir-dining.com', max_length=254)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=8.875, max_digits=5)),
                ('address', models.TextField(default='42 Gourmet Avenue, Manhattan, New York, NY 10001')),
                ('opening_hours', models.TextField(default='Mon-Thu: 5PM - 10PM | Fri-Sat: 5PM - 11PM | Sun: 4PM - 9:30PM')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('location', models.CharField(choices=[('main', 'Main Dining Room'), ('window', 'Window Area'), ('terrace', 'Outdoor Terrace'), ('private', 'Private Dining')], default='main', max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
    ]
